apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-private-api
  # namespace: public  >>>   SE ELIMINA !!
data:
  # SE CREA UNA "VARIABLE PARA REMPLAZARLA EN EL AMBIENTE CORRECTO"
  PRIVATE_API: PRIVATE_API_URL