apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: public-stage

# deprecated
commonLabels:
  app: public-api
  team: devops

# labels:
# - pairs:
#     app: public-api
#     team: devops
#   includeSelectors: true

commonAnnotations:
  note: This is STAGE deployment

resources:
- ns.yaml
- ../../base

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/
patchesStrategicMerge:
- deploy-strategic-patch.yaml

# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
# https://fabianlee.org/2022/04/15/kubernetes-kustomize-transformations-with-patchesjson6902/
# yaml file patch


  # In-line patch
patches:
- path: cm-patch.yaml
  target:
    kind: ConfigMap
    name: cm-private-api
- path: ing-patch.yaml
  target:
    kind: Ingress
    name: public-api
- patch: |-
    - op: add
      path: /spec/type
      value: ClusterIP
  target:
    kind: Service
    name: public-api



# Image patch
    #newTag: 1.0.0  # <- cambiar la version correcta.
images:
- name: KUSTOMIZE-DEFINED
  newName: emoralesc/kubelabs_publicapi
  newTag: 1.0.0  # <- cambiar la version correcta.
