apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Stage-Public-API
spec:
  destination:
    namespace: public-stage
    server: https://kubernetes.default.svc
  source:
    path: public-api/overlays/stage
    repoURL: https://github.com/Edmoralesc/Ops
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
